spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ten_database
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect